name: publish-package

on:
  release:
    types: [published, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write      # Required for tokenless npm Trusted Publishing
      packages: write      # Required to write to GitHub Packages
    steps:
      - uses: actions/setup-node@v4
      
      - name: install
        run: npm install
        if: ${{ always() }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}

      - name: build package
        run: npm run build:src

      - name: Setup Node for npm
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org' # Points to public npm

      - name: publish package
        working-directory: ./lib
        run: npm publish
        if: ${{ always() }}

      - name: Setup Node for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com' # Overwrites registry path to GitHub
          scope: '@stamcat' # Binds the package structure explicitly to your GitHub scope

      - name: publish package
        working-directory: ./lib
        run: npm publish --registry https://npm.pkg.github.com
        if: ${{ always() }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
